api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "wholesale-minimum-order"
type = "function"
uid = "2dd482eb-1ad6-fa83-f387-d9824c6117a375337cbd"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.input.variables]
  namespace = "$app:b2b_toolkit"
  key = "function_variables"
